name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore TTVProxy.sln

    - name: Build solution
      run: msbuild TTVProxy.sln -t:rebuild -property:Configuration=Release

    - name: Show content
      run: dir .\src\TTVProxy_console\bin\Release\

    - name: Display Build Number
      run: echo "Build Number: ${{ github.run_number }}"
